version: '3.8'

services:
  bot:
    build: .
    container_name: medusaxd-torrent-bot
    restart: unless-stopped
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_USER_IDS=${ADMIN_USER_IDS}
      - SUPER_ADMIN_ID=${SUPER_ADMIN_ID}
      - DATABASE_URL=postgresql://postgres:password@db:5432/medusaxd_bot
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: postgres:15-alpine
    container_name: medusaxd-bot-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=medusaxd_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  bot-network:
    driver: bridge
