services:
  - type: worker
    name: torrent-uploader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: SUPER_ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
        # Example Supabase URL format:
        # postgresql://postgres:[password]@db.[project-ref].supabase.co:5432/postgres
      - key: BOT_NAME
        value: MedusaXD Torrent Downloader
      - key: MAX_FILE_SIZE
        value: "2048"
      - key: LOG_LEVEL
        value: INFO
      - key: WORKERS
        value: "4"
      - key: SESSION_NAME
        value: medusaxd_bot_session
